### ISSUE TITLE
Konfiguraatiossa olevat typot/virheet ovat vaikeita löytää

### ISSUE THREAD

**Issue by esalep** [CommunityHiQ/Frends.Community.Apache.Parquet#10]
Konfiguraation vikasietoisuus on pieni: jos siinä on yksikin typo, esim. "type" -> "typr" , niin taski ei sitä havaitse, vaan palauttaa poikkeuksen.

* Tämä voitaisiin välttää lisäämällä skeematarkastus ennen konfiguraation lukemista.
* Konfiguraation lukeminen voisi olla omassa try-catch rakenteessaan, josta pystyisi päättelemään onko vika skeemassa vai aineistossa.

**Comment by Svenskapojkarna** [comment]
This issue has been moved to https://github.com/CommunityHiQ/Frends.Community.Apache/issues/2
